import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '700'], // 400 = Regular, 700 = Bold
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="pt-BR" className={poppins.className}>
        <body>{children}</body>
        </html>
    )
}
